services:
  db:
    image: postgres:15.0-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    depends_on:
      db:
        condition: service_healthy
    build: ./server
    ports:
      - 4000:4000
      - 5001:5001
    volumes:
      - ./server/src:/app/src
  client:
    environment: 
      CHOKIDAR_USEPOLLING: "true"
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
